# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c46d3626a40f4c784b564adb32ebd4671fe84172a2fda7bc2b8387e26d5f9c3603c5cd61ecf9d71a6dcad839a0585987cfe56e1ec7c4d783def570987d65a2bf

test:
  secret_key_base: e8585b7981d95fc95922f7b68394edb48ddbcad8180d4842a72f9a3b4296b537b1ad70b38a21c64234575ea99e4917dbfddd1a5854a98e1b80509d123e886ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
